# Generated by Django 4.2.4 on 2023-08-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('issuer_name', models.CharField(max_length=200)),
            ],
        ),
    ]
