# Generated by Django 4.2.4 on 2023-08-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issuer_name',
            new_name='Course',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]
